# Render deployment configuration
# This file tells Render how to deploy your static site

# Build command (not needed for static sites, but included for completeness)
build: echo "Static site - no build required"

# Start command for static site
start: python -m http.server $PORT

# Environment
PYTHON_VERSION: 3.9.0

# Static site configuration
STATIC_SITE: true

# Health check endpoint
HEALTH_CHECK_PATH: /

# Custom headers for security and performance
CUSTOM_HEADERS: |
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
  X-XSS-Protection: 1; mode=block
  Referrer-Policy: strict-origin-when-cross-origin
  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://www.google-analytics.com; frame-src 'none';
